[BUGFIX] iwlwifi: mvm: use do_div in ftm to avoid problems with 32-bit platforms
There is an issue with some 64-bit divisions on 32-bit platforms that
cause the following warning:

ERROR: "__divdi3" [drivers/net/wireless/intel/iwlwifi/mvm/iwlmvm.ko] undefined!

This is because gcc uses a helper function that is implemented in one
of its libraries that is not linked in the kernel.

To prevent this issue, we should use the do_div() helper function when
making divisions on 64-bit values.  Do this in
iwl_mvm_debug_range_resp() to avoid the problem.

type=bugfix
fixes=I9dfb64db770801084f21deb8d7ef436835e18fc8
ticket=none

Change-Id: Icf85b9f7f8a27c4133891b896b6aa81670fe1723
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/209016
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/209855
x-iwlwifi-stack-dev: 5b26fc795935870beb18f9fa8911364a071c6ef2